#pragma once

#include <ExampleScript.hpp>
#include <ClockedScript.hpp>
#include <ExampleClockedScript.hpp>
#include <ReloadSceneScript.hpp>
#include <CameraScript.hpp>
#include <ExampleCameraScript.hpp>
#include <CursorAnimation.hpp>
#include <ButtonScript.hpp>
#include <Weapons/WeaponAmmunition/BulletScript.hpp>
#include <Weapons/WeaponAmmunition/GrenadeScript.hpp>
#include <Weapons/WeaponHolders/GrenadeBunchScript.hpp>
#include <Weapons/WeaponHolders/StraightWeaponScript.hpp>
#include <Weapons/WeaponHolders/WeaponScript.hpp>
#include <Weapons/WeaponHolders/WeaponStorage.hpp>
#include <Weapons/WeaponGenerator.hpp>
#include <PlayerAnimation.hpp>
#include <NetworkPlayerScript.hpp>
#include <Network/NetworkManagerClientScript.hpp>
#include <Network/NetworkManagerServerScript.hpp>
#include <PlayerControlledBox/PlayerControlledBoxClient.hpp>
#include <PlayerControlledBox/PlayerControlledBoxServer.hpp>
#include <PlayerProgress/HealthBar.hpp>
#include <PlayerProgress/HealthBarHolder.hpp>
#include <DeleteScript.hpp>
#include <MusicManager.hpp>
#include <Wall.hpp>

