// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scene.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_scene_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_scene_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_scene_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_scene_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_scene_2eproto;
namespace serial {
class BasicGameObject;
struct BasicGameObjectDefaultTypeInternal;
extern BasicGameObjectDefaultTypeInternal _BasicGameObject_default_instance_;
class BasicScript;
struct BasicScriptDefaultTypeInternal;
extern BasicScriptDefaultTypeInternal _BasicScript_default_instance_;
class GameObject;
struct GameObjectDefaultTypeInternal;
extern GameObjectDefaultTypeInternal _GameObject_default_instance_;
class Position;
struct PositionDefaultTypeInternal;
extern PositionDefaultTypeInternal _Position_default_instance_;
class Scene;
struct SceneDefaultTypeInternal;
extern SceneDefaultTypeInternal _Scene_default_instance_;
class Script;
struct ScriptDefaultTypeInternal;
extern ScriptDefaultTypeInternal _Script_default_instance_;
class Sprite;
struct SpriteDefaultTypeInternal;
extern SpriteDefaultTypeInternal _Sprite_default_instance_;
class Sprite_Scale;
struct Sprite_ScaleDefaultTypeInternal;
extern Sprite_ScaleDefaultTypeInternal _Sprite_Scale_default_instance_;
}  // namespace serial
PROTOBUF_NAMESPACE_OPEN
template<> ::serial::BasicGameObject* Arena::CreateMaybeMessage<::serial::BasicGameObject>(Arena*);
template<> ::serial::BasicScript* Arena::CreateMaybeMessage<::serial::BasicScript>(Arena*);
template<> ::serial::GameObject* Arena::CreateMaybeMessage<::serial::GameObject>(Arena*);
template<> ::serial::Position* Arena::CreateMaybeMessage<::serial::Position>(Arena*);
template<> ::serial::Scene* Arena::CreateMaybeMessage<::serial::Scene>(Arena*);
template<> ::serial::Script* Arena::CreateMaybeMessage<::serial::Script>(Arena*);
template<> ::serial::Sprite* Arena::CreateMaybeMessage<::serial::Sprite>(Arena*);
template<> ::serial::Sprite_Scale* Arena::CreateMaybeMessage<::serial::Sprite_Scale>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace serial {

enum RenderLayer : int {
  BACKGROUND = 0,
  BACKGROUND1 = 1,
  BACKGROUND2 = 2,
  BACKGROUND3 = 3,
  FOREGROUND = 4,
  FOREGROUND1 = 5,
  FOREGROUND2 = 6,
  FOREGROUND3 = 7,
  ONTOP = 8,
  RenderLayer_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RenderLayer_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RenderLayer_IsValid(int value);
constexpr RenderLayer RenderLayer_MIN = BACKGROUND;
constexpr RenderLayer RenderLayer_MAX = ONTOP;
constexpr int RenderLayer_ARRAYSIZE = RenderLayer_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RenderLayer_descriptor();
template<typename T>
inline const std::string& RenderLayer_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RenderLayer>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RenderLayer_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RenderLayer_descriptor(), enum_t_value);
}
inline bool RenderLayer_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RenderLayer* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RenderLayer>(
    RenderLayer_descriptor(), name, value);
}
enum Box2DType : int {
  STATIC = 0,
  DYNAMIC = 1,
  Box2DType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Box2DType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Box2DType_IsValid(int value);
constexpr Box2DType Box2DType_MIN = STATIC;
constexpr Box2DType Box2DType_MAX = DYNAMIC;
constexpr int Box2DType_ARRAYSIZE = Box2DType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Box2DType_descriptor();
template<typename T>
inline const std::string& Box2DType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Box2DType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Box2DType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Box2DType_descriptor(), enum_t_value);
}
inline bool Box2DType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Box2DType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Box2DType>(
    Box2DType_descriptor(), name, value);
}
// ===================================================================

class Scene final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:serial.Scene) */ {
 public:
  inline Scene() : Scene(nullptr) {}
  ~Scene() override;
  explicit constexpr Scene(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Scene(const Scene& from);
  Scene(Scene&& from) noexcept
    : Scene() {
    *this = ::std::move(from);
  }

  inline Scene& operator=(const Scene& from) {
    CopyFrom(from);
    return *this;
  }
  inline Scene& operator=(Scene&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Scene& default_instance() {
    return *internal_default_instance();
  }
  static inline const Scene* internal_default_instance() {
    return reinterpret_cast<const Scene*>(
               &_Scene_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Scene& a, Scene& b) {
    a.Swap(&b);
  }
  inline void Swap(Scene* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Scene* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Scene* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Scene>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Scene& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Scene& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Scene* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "serial.Scene";
  }
  protected:
  explicit Scene(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBox2DPositionFieldNumber = 2,
  };
  // .serial.Position box2d_position = 2;
  bool has_box2d_position() const;
  private:
  bool _internal_has_box2d_position() const;
  public:
  void clear_box2d_position();
  const ::serial::Position& box2d_position() const;
  PROTOBUF_NODISCARD ::serial::Position* release_box2d_position();
  ::serial::Position* mutable_box2d_position();
  void set_allocated_box2d_position(::serial::Position* box2d_position);
  private:
  const ::serial::Position& _internal_box2d_position() const;
  ::serial::Position* _internal_mutable_box2d_position();
  public:
  void unsafe_arena_set_allocated_box2d_position(
      ::serial::Position* box2d_position);
  ::serial::Position* unsafe_arena_release_box2d_position();

  // @@protoc_insertion_point(class_scope:serial.Scene)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::serial::Position* box2d_position_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scene_2eproto;
};
// -------------------------------------------------------------------

class GameObject final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:serial.GameObject) */ {
 public:
  inline GameObject() : GameObject(nullptr) {}
  ~GameObject() override;
  explicit constexpr GameObject(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameObject(const GameObject& from);
  GameObject(GameObject&& from) noexcept
    : GameObject() {
    *this = ::std::move(from);
  }

  inline GameObject& operator=(const GameObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameObject& operator=(GameObject&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameObject& default_instance() {
    return *internal_default_instance();
  }
  enum GameObjectInstanceCase {
    kBasicGameObject = 1,
    GAME_OBJECT_INSTANCE_NOT_SET = 0,
  };

  static inline const GameObject* internal_default_instance() {
    return reinterpret_cast<const GameObject*>(
               &_GameObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GameObject& a, GameObject& b) {
    a.Swap(&b);
  }
  inline void Swap(GameObject* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameObject* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameObject* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameObject>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameObject& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GameObject& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameObject* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "serial.GameObject";
  }
  protected:
  explicit GameObject(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBasicGameObjectFieldNumber = 1,
  };
  // .serial.BasicGameObject basic_game_object = 1;
  bool has_basic_game_object() const;
  private:
  bool _internal_has_basic_game_object() const;
  public:
  void clear_basic_game_object();
  const ::serial::BasicGameObject& basic_game_object() const;
  PROTOBUF_NODISCARD ::serial::BasicGameObject* release_basic_game_object();
  ::serial::BasicGameObject* mutable_basic_game_object();
  void set_allocated_basic_game_object(::serial::BasicGameObject* basic_game_object);
  private:
  const ::serial::BasicGameObject& _internal_basic_game_object() const;
  ::serial::BasicGameObject* _internal_mutable_basic_game_object();
  public:
  void unsafe_arena_set_allocated_basic_game_object(
      ::serial::BasicGameObject* basic_game_object);
  ::serial::BasicGameObject* unsafe_arena_release_basic_game_object();

  void clear_game_object_instance();
  GameObjectInstanceCase game_object_instance_case() const;
  // @@protoc_insertion_point(class_scope:serial.GameObject)
 private:
  class _Internal;
  void set_has_basic_game_object();

  inline bool has_game_object_instance() const;
  inline void clear_has_game_object_instance();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union GameObjectInstanceUnion {
    constexpr GameObjectInstanceUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::serial::BasicGameObject* basic_game_object_;
  } game_object_instance_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint32_t _oneof_case_[1];

  friend struct ::TableStruct_scene_2eproto;
};
// -------------------------------------------------------------------

class Script final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:serial.Script) */ {
 public:
  inline Script() : Script(nullptr) {}
  ~Script() override;
  explicit constexpr Script(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Script(const Script& from);
  Script(Script&& from) noexcept
    : Script() {
    *this = ::std::move(from);
  }

  inline Script& operator=(const Script& from) {
    CopyFrom(from);
    return *this;
  }
  inline Script& operator=(Script&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Script& default_instance() {
    return *internal_default_instance();
  }
  enum ScriptInstanceCase {
    kBasicScript = 1,
    SCRIPT_INSTANCE_NOT_SET = 0,
  };

  static inline const Script* internal_default_instance() {
    return reinterpret_cast<const Script*>(
               &_Script_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Script& a, Script& b) {
    a.Swap(&b);
  }
  inline void Swap(Script* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Script* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Script* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Script>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Script& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Script& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Script* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "serial.Script";
  }
  protected:
  explicit Script(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBasicScriptFieldNumber = 1,
  };
  // .serial.BasicScript basic_script = 1;
  bool has_basic_script() const;
  private:
  bool _internal_has_basic_script() const;
  public:
  void clear_basic_script();
  const ::serial::BasicScript& basic_script() const;
  PROTOBUF_NODISCARD ::serial::BasicScript* release_basic_script();
  ::serial::BasicScript* mutable_basic_script();
  void set_allocated_basic_script(::serial::BasicScript* basic_script);
  private:
  const ::serial::BasicScript& _internal_basic_script() const;
  ::serial::BasicScript* _internal_mutable_basic_script();
  public:
  void unsafe_arena_set_allocated_basic_script(
      ::serial::BasicScript* basic_script);
  ::serial::BasicScript* unsafe_arena_release_basic_script();

  void clear_script_instance();
  ScriptInstanceCase script_instance_case() const;
  // @@protoc_insertion_point(class_scope:serial.Script)
 private:
  class _Internal;
  void set_has_basic_script();

  inline bool has_script_instance() const;
  inline void clear_has_script_instance();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union ScriptInstanceUnion {
    constexpr ScriptInstanceUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::serial::BasicScript* basic_script_;
  } script_instance_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint32_t _oneof_case_[1];

  friend struct ::TableStruct_scene_2eproto;
};
// -------------------------------------------------------------------

class BasicScript final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:serial.BasicScript) */ {
 public:
  inline BasicScript() : BasicScript(nullptr) {}
  explicit constexpr BasicScript(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BasicScript(const BasicScript& from);
  BasicScript(BasicScript&& from) noexcept
    : BasicScript() {
    *this = ::std::move(from);
  }

  inline BasicScript& operator=(const BasicScript& from) {
    CopyFrom(from);
    return *this;
  }
  inline BasicScript& operator=(BasicScript&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BasicScript& default_instance() {
    return *internal_default_instance();
  }
  static inline const BasicScript* internal_default_instance() {
    return reinterpret_cast<const BasicScript*>(
               &_BasicScript_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BasicScript& a, BasicScript& b) {
    a.Swap(&b);
  }
  inline void Swap(BasicScript* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BasicScript* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BasicScript* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BasicScript>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const BasicScript& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const BasicScript& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "serial.BasicScript";
  }
  protected:
  explicit BasicScript(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:serial.BasicScript)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scene_2eproto;
};
// -------------------------------------------------------------------

class BasicGameObject final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:serial.BasicGameObject) */ {
 public:
  inline BasicGameObject() : BasicGameObject(nullptr) {}
  ~BasicGameObject() override;
  explicit constexpr BasicGameObject(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BasicGameObject(const BasicGameObject& from);
  BasicGameObject(BasicGameObject&& from) noexcept
    : BasicGameObject() {
    *this = ::std::move(from);
  }

  inline BasicGameObject& operator=(const BasicGameObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline BasicGameObject& operator=(BasicGameObject&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BasicGameObject& default_instance() {
    return *internal_default_instance();
  }
  static inline const BasicGameObject* internal_default_instance() {
    return reinterpret_cast<const BasicGameObject*>(
               &_BasicGameObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(BasicGameObject& a, BasicGameObject& b) {
    a.Swap(&b);
  }
  inline void Swap(BasicGameObject* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BasicGameObject* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BasicGameObject* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BasicGameObject>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BasicGameObject& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const BasicGameObject& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BasicGameObject* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "serial.BasicGameObject";
  }
  protected:
  explicit BasicGameObject(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChildrenObjectsFieldNumber = 1,
    kChildrenScriptsFieldNumber = 2,
    kTagsFieldNumber = 3,
    kSpriteFieldNumber = 4,
    kVisibleFieldNumber = 5,
    kBox2DTypeFieldNumber = 6,
    kRenderLayerFieldNumber = 7,
  };
  // repeated .serial.GameObject children_objects = 1;
  int children_objects_size() const;
  private:
  int _internal_children_objects_size() const;
  public:
  void clear_children_objects();
  ::serial::GameObject* mutable_children_objects(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::serial::GameObject >*
      mutable_children_objects();
  private:
  const ::serial::GameObject& _internal_children_objects(int index) const;
  ::serial::GameObject* _internal_add_children_objects();
  public:
  const ::serial::GameObject& children_objects(int index) const;
  ::serial::GameObject* add_children_objects();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::serial::GameObject >&
      children_objects() const;

  // repeated .serial.Script children_scripts = 2;
  int children_scripts_size() const;
  private:
  int _internal_children_scripts_size() const;
  public:
  void clear_children_scripts();
  ::serial::Script* mutable_children_scripts(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::serial::Script >*
      mutable_children_scripts();
  private:
  const ::serial::Script& _internal_children_scripts(int index) const;
  ::serial::Script* _internal_add_children_scripts();
  public:
  const ::serial::Script& children_scripts(int index) const;
  ::serial::Script* add_children_scripts();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::serial::Script >&
      children_scripts() const;

  // repeated string tags = 3;
  int tags_size() const;
  private:
  int _internal_tags_size() const;
  public:
  void clear_tags();
  const std::string& tags(int index) const;
  std::string* mutable_tags(int index);
  void set_tags(int index, const std::string& value);
  void set_tags(int index, std::string&& value);
  void set_tags(int index, const char* value);
  void set_tags(int index, const char* value, size_t size);
  std::string* add_tags();
  void add_tags(const std::string& value);
  void add_tags(std::string&& value);
  void add_tags(const char* value);
  void add_tags(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& tags() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_tags();
  private:
  const std::string& _internal_tags(int index) const;
  std::string* _internal_add_tags();
  public:

  // .serial.Sprite sprite = 4;
  bool has_sprite() const;
  private:
  bool _internal_has_sprite() const;
  public:
  void clear_sprite();
  const ::serial::Sprite& sprite() const;
  PROTOBUF_NODISCARD ::serial::Sprite* release_sprite();
  ::serial::Sprite* mutable_sprite();
  void set_allocated_sprite(::serial::Sprite* sprite);
  private:
  const ::serial::Sprite& _internal_sprite() const;
  ::serial::Sprite* _internal_mutable_sprite();
  public:
  void unsafe_arena_set_allocated_sprite(
      ::serial::Sprite* sprite);
  ::serial::Sprite* unsafe_arena_release_sprite();

  // bool visible = 5;
  void clear_visible();
  bool visible() const;
  void set_visible(bool value);
  private:
  bool _internal_visible() const;
  void _internal_set_visible(bool value);
  public:

  // .serial.Box2DType box2d_type = 6;
  void clear_box2d_type();
  ::serial::Box2DType box2d_type() const;
  void set_box2d_type(::serial::Box2DType value);
  private:
  ::serial::Box2DType _internal_box2d_type() const;
  void _internal_set_box2d_type(::serial::Box2DType value);
  public:

  // .serial.RenderLayer render_layer = 7;
  void clear_render_layer();
  ::serial::RenderLayer render_layer() const;
  void set_render_layer(::serial::RenderLayer value);
  private:
  ::serial::RenderLayer _internal_render_layer() const;
  void _internal_set_render_layer(::serial::RenderLayer value);
  public:

  // @@protoc_insertion_point(class_scope:serial.BasicGameObject)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::serial::GameObject > children_objects_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::serial::Script > children_scripts_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> tags_;
  ::serial::Sprite* sprite_;
  bool visible_;
  int box2d_type_;
  int render_layer_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scene_2eproto;
};
// -------------------------------------------------------------------

class Position final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:serial.Position) */ {
 public:
  inline Position() : Position(nullptr) {}
  ~Position() override;
  explicit constexpr Position(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Position(const Position& from);
  Position(Position&& from) noexcept
    : Position() {
    *this = ::std::move(from);
  }

  inline Position& operator=(const Position& from) {
    CopyFrom(from);
    return *this;
  }
  inline Position& operator=(Position&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Position& default_instance() {
    return *internal_default_instance();
  }
  static inline const Position* internal_default_instance() {
    return reinterpret_cast<const Position*>(
               &_Position_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Position& a, Position& b) {
    a.Swap(&b);
  }
  inline void Swap(Position* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Position* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Position* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Position>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Position& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Position& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Position* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "serial.Position";
  }
  protected:
  explicit Position(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:serial.Position)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scene_2eproto;
};
// -------------------------------------------------------------------

class Sprite_Scale final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:serial.Sprite.Scale) */ {
 public:
  inline Sprite_Scale() : Sprite_Scale(nullptr) {}
  ~Sprite_Scale() override;
  explicit constexpr Sprite_Scale(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Sprite_Scale(const Sprite_Scale& from);
  Sprite_Scale(Sprite_Scale&& from) noexcept
    : Sprite_Scale() {
    *this = ::std::move(from);
  }

  inline Sprite_Scale& operator=(const Sprite_Scale& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sprite_Scale& operator=(Sprite_Scale&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Sprite_Scale& default_instance() {
    return *internal_default_instance();
  }
  static inline const Sprite_Scale* internal_default_instance() {
    return reinterpret_cast<const Sprite_Scale*>(
               &_Sprite_Scale_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Sprite_Scale& a, Sprite_Scale& b) {
    a.Swap(&b);
  }
  inline void Swap(Sprite_Scale* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sprite_Scale* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Sprite_Scale* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Sprite_Scale>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Sprite_Scale& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Sprite_Scale& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sprite_Scale* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "serial.Sprite.Scale";
  }
  protected:
  explicit Sprite_Scale(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScaleXFieldNumber = 1,
    kScaleYFieldNumber = 2,
  };
  // float scale_x = 1;
  void clear_scale_x();
  float scale_x() const;
  void set_scale_x(float value);
  private:
  float _internal_scale_x() const;
  void _internal_set_scale_x(float value);
  public:

  // float scale_y = 2;
  void clear_scale_y();
  float scale_y() const;
  void set_scale_y(float value);
  private:
  float _internal_scale_y() const;
  void _internal_set_scale_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:serial.Sprite.Scale)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float scale_x_;
  float scale_y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scene_2eproto;
};
// -------------------------------------------------------------------

class Sprite final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:serial.Sprite) */ {
 public:
  inline Sprite() : Sprite(nullptr) {}
  ~Sprite() override;
  explicit constexpr Sprite(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Sprite(const Sprite& from);
  Sprite(Sprite&& from) noexcept
    : Sprite() {
    *this = ::std::move(from);
  }

  inline Sprite& operator=(const Sprite& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sprite& operator=(Sprite&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Sprite& default_instance() {
    return *internal_default_instance();
  }
  static inline const Sprite* internal_default_instance() {
    return reinterpret_cast<const Sprite*>(
               &_Sprite_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(Sprite& a, Sprite& b) {
    a.Swap(&b);
  }
  inline void Swap(Sprite* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sprite* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Sprite* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Sprite>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Sprite& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Sprite& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sprite* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "serial.Sprite";
  }
  protected:
  explicit Sprite(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Sprite_Scale Scale;

  // accessors -------------------------------------------------------

  enum : int {
    kTexturePathFieldNumber = 1,
    kPositionFieldNumber = 2,
    kScaleFieldNumber = 5,
  };
  // string texture_path = 1;
  void clear_texture_path();
  const std::string& texture_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_texture_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_texture_path();
  PROTOBUF_NODISCARD std::string* release_texture_path();
  void set_allocated_texture_path(std::string* texture_path);
  private:
  const std::string& _internal_texture_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_texture_path(const std::string& value);
  std::string* _internal_mutable_texture_path();
  public:

  // .serial.Position position = 2;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::serial::Position& position() const;
  PROTOBUF_NODISCARD ::serial::Position* release_position();
  ::serial::Position* mutable_position();
  void set_allocated_position(::serial::Position* position);
  private:
  const ::serial::Position& _internal_position() const;
  ::serial::Position* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::serial::Position* position);
  ::serial::Position* unsafe_arena_release_position();

  // .serial.Sprite.Scale scale = 5;
  bool has_scale() const;
  private:
  bool _internal_has_scale() const;
  public:
  void clear_scale();
  const ::serial::Sprite_Scale& scale() const;
  PROTOBUF_NODISCARD ::serial::Sprite_Scale* release_scale();
  ::serial::Sprite_Scale* mutable_scale();
  void set_allocated_scale(::serial::Sprite_Scale* scale);
  private:
  const ::serial::Sprite_Scale& _internal_scale() const;
  ::serial::Sprite_Scale* _internal_mutable_scale();
  public:
  void unsafe_arena_set_allocated_scale(
      ::serial::Sprite_Scale* scale);
  ::serial::Sprite_Scale* unsafe_arena_release_scale();

  // @@protoc_insertion_point(class_scope:serial.Sprite)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr texture_path_;
  ::serial::Position* position_;
  ::serial::Sprite_Scale* scale_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scene_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Scene

// .serial.Position box2d_position = 2;
inline bool Scene::_internal_has_box2d_position() const {
  return this != internal_default_instance() && box2d_position_ != nullptr;
}
inline bool Scene::has_box2d_position() const {
  return _internal_has_box2d_position();
}
inline void Scene::clear_box2d_position() {
  if (GetArenaForAllocation() == nullptr && box2d_position_ != nullptr) {
    delete box2d_position_;
  }
  box2d_position_ = nullptr;
}
inline const ::serial::Position& Scene::_internal_box2d_position() const {
  const ::serial::Position* p = box2d_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::serial::Position&>(
      ::serial::_Position_default_instance_);
}
inline const ::serial::Position& Scene::box2d_position() const {
  // @@protoc_insertion_point(field_get:serial.Scene.box2d_position)
  return _internal_box2d_position();
}
inline void Scene::unsafe_arena_set_allocated_box2d_position(
    ::serial::Position* box2d_position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(box2d_position_);
  }
  box2d_position_ = box2d_position;
  if (box2d_position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:serial.Scene.box2d_position)
}
inline ::serial::Position* Scene::release_box2d_position() {
  
  ::serial::Position* temp = box2d_position_;
  box2d_position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::serial::Position* Scene::unsafe_arena_release_box2d_position() {
  // @@protoc_insertion_point(field_release:serial.Scene.box2d_position)
  
  ::serial::Position* temp = box2d_position_;
  box2d_position_ = nullptr;
  return temp;
}
inline ::serial::Position* Scene::_internal_mutable_box2d_position() {
  
  if (box2d_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::serial::Position>(GetArenaForAllocation());
    box2d_position_ = p;
  }
  return box2d_position_;
}
inline ::serial::Position* Scene::mutable_box2d_position() {
  ::serial::Position* _msg = _internal_mutable_box2d_position();
  // @@protoc_insertion_point(field_mutable:serial.Scene.box2d_position)
  return _msg;
}
inline void Scene::set_allocated_box2d_position(::serial::Position* box2d_position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete box2d_position_;
  }
  if (box2d_position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::serial::Position>::GetOwningArena(box2d_position);
    if (message_arena != submessage_arena) {
      box2d_position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, box2d_position, submessage_arena);
    }
    
  } else {
    
  }
  box2d_position_ = box2d_position;
  // @@protoc_insertion_point(field_set_allocated:serial.Scene.box2d_position)
}

// -------------------------------------------------------------------

// GameObject

// .serial.BasicGameObject basic_game_object = 1;
inline bool GameObject::_internal_has_basic_game_object() const {
  return game_object_instance_case() == kBasicGameObject;
}
inline bool GameObject::has_basic_game_object() const {
  return _internal_has_basic_game_object();
}
inline void GameObject::set_has_basic_game_object() {
  _oneof_case_[0] = kBasicGameObject;
}
inline void GameObject::clear_basic_game_object() {
  if (_internal_has_basic_game_object()) {
    if (GetArenaForAllocation() == nullptr) {
      delete game_object_instance_.basic_game_object_;
    }
    clear_has_game_object_instance();
  }
}
inline ::serial::BasicGameObject* GameObject::release_basic_game_object() {
  // @@protoc_insertion_point(field_release:serial.GameObject.basic_game_object)
  if (_internal_has_basic_game_object()) {
    clear_has_game_object_instance();
      ::serial::BasicGameObject* temp = game_object_instance_.basic_game_object_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    game_object_instance_.basic_game_object_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::serial::BasicGameObject& GameObject::_internal_basic_game_object() const {
  return _internal_has_basic_game_object()
      ? *game_object_instance_.basic_game_object_
      : reinterpret_cast< ::serial::BasicGameObject&>(::serial::_BasicGameObject_default_instance_);
}
inline const ::serial::BasicGameObject& GameObject::basic_game_object() const {
  // @@protoc_insertion_point(field_get:serial.GameObject.basic_game_object)
  return _internal_basic_game_object();
}
inline ::serial::BasicGameObject* GameObject::unsafe_arena_release_basic_game_object() {
  // @@protoc_insertion_point(field_unsafe_arena_release:serial.GameObject.basic_game_object)
  if (_internal_has_basic_game_object()) {
    clear_has_game_object_instance();
    ::serial::BasicGameObject* temp = game_object_instance_.basic_game_object_;
    game_object_instance_.basic_game_object_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GameObject::unsafe_arena_set_allocated_basic_game_object(::serial::BasicGameObject* basic_game_object) {
  clear_game_object_instance();
  if (basic_game_object) {
    set_has_basic_game_object();
    game_object_instance_.basic_game_object_ = basic_game_object;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:serial.GameObject.basic_game_object)
}
inline ::serial::BasicGameObject* GameObject::_internal_mutable_basic_game_object() {
  if (!_internal_has_basic_game_object()) {
    clear_game_object_instance();
    set_has_basic_game_object();
    game_object_instance_.basic_game_object_ = CreateMaybeMessage< ::serial::BasicGameObject >(GetArenaForAllocation());
  }
  return game_object_instance_.basic_game_object_;
}
inline ::serial::BasicGameObject* GameObject::mutable_basic_game_object() {
  ::serial::BasicGameObject* _msg = _internal_mutable_basic_game_object();
  // @@protoc_insertion_point(field_mutable:serial.GameObject.basic_game_object)
  return _msg;
}

inline bool GameObject::has_game_object_instance() const {
  return game_object_instance_case() != GAME_OBJECT_INSTANCE_NOT_SET;
}
inline void GameObject::clear_has_game_object_instance() {
  _oneof_case_[0] = GAME_OBJECT_INSTANCE_NOT_SET;
}
inline GameObject::GameObjectInstanceCase GameObject::game_object_instance_case() const {
  return GameObject::GameObjectInstanceCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Script

// .serial.BasicScript basic_script = 1;
inline bool Script::_internal_has_basic_script() const {
  return script_instance_case() == kBasicScript;
}
inline bool Script::has_basic_script() const {
  return _internal_has_basic_script();
}
inline void Script::set_has_basic_script() {
  _oneof_case_[0] = kBasicScript;
}
inline void Script::clear_basic_script() {
  if (_internal_has_basic_script()) {
    if (GetArenaForAllocation() == nullptr) {
      delete script_instance_.basic_script_;
    }
    clear_has_script_instance();
  }
}
inline ::serial::BasicScript* Script::release_basic_script() {
  // @@protoc_insertion_point(field_release:serial.Script.basic_script)
  if (_internal_has_basic_script()) {
    clear_has_script_instance();
      ::serial::BasicScript* temp = script_instance_.basic_script_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    script_instance_.basic_script_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::serial::BasicScript& Script::_internal_basic_script() const {
  return _internal_has_basic_script()
      ? *script_instance_.basic_script_
      : reinterpret_cast< ::serial::BasicScript&>(::serial::_BasicScript_default_instance_);
}
inline const ::serial::BasicScript& Script::basic_script() const {
  // @@protoc_insertion_point(field_get:serial.Script.basic_script)
  return _internal_basic_script();
}
inline ::serial::BasicScript* Script::unsafe_arena_release_basic_script() {
  // @@protoc_insertion_point(field_unsafe_arena_release:serial.Script.basic_script)
  if (_internal_has_basic_script()) {
    clear_has_script_instance();
    ::serial::BasicScript* temp = script_instance_.basic_script_;
    script_instance_.basic_script_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Script::unsafe_arena_set_allocated_basic_script(::serial::BasicScript* basic_script) {
  clear_script_instance();
  if (basic_script) {
    set_has_basic_script();
    script_instance_.basic_script_ = basic_script;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:serial.Script.basic_script)
}
inline ::serial::BasicScript* Script::_internal_mutable_basic_script() {
  if (!_internal_has_basic_script()) {
    clear_script_instance();
    set_has_basic_script();
    script_instance_.basic_script_ = CreateMaybeMessage< ::serial::BasicScript >(GetArenaForAllocation());
  }
  return script_instance_.basic_script_;
}
inline ::serial::BasicScript* Script::mutable_basic_script() {
  ::serial::BasicScript* _msg = _internal_mutable_basic_script();
  // @@protoc_insertion_point(field_mutable:serial.Script.basic_script)
  return _msg;
}

inline bool Script::has_script_instance() const {
  return script_instance_case() != SCRIPT_INSTANCE_NOT_SET;
}
inline void Script::clear_has_script_instance() {
  _oneof_case_[0] = SCRIPT_INSTANCE_NOT_SET;
}
inline Script::ScriptInstanceCase Script::script_instance_case() const {
  return Script::ScriptInstanceCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// BasicScript

// -------------------------------------------------------------------

// BasicGameObject

// repeated .serial.GameObject children_objects = 1;
inline int BasicGameObject::_internal_children_objects_size() const {
  return children_objects_.size();
}
inline int BasicGameObject::children_objects_size() const {
  return _internal_children_objects_size();
}
inline void BasicGameObject::clear_children_objects() {
  children_objects_.Clear();
}
inline ::serial::GameObject* BasicGameObject::mutable_children_objects(int index) {
  // @@protoc_insertion_point(field_mutable:serial.BasicGameObject.children_objects)
  return children_objects_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::serial::GameObject >*
BasicGameObject::mutable_children_objects() {
  // @@protoc_insertion_point(field_mutable_list:serial.BasicGameObject.children_objects)
  return &children_objects_;
}
inline const ::serial::GameObject& BasicGameObject::_internal_children_objects(int index) const {
  return children_objects_.Get(index);
}
inline const ::serial::GameObject& BasicGameObject::children_objects(int index) const {
  // @@protoc_insertion_point(field_get:serial.BasicGameObject.children_objects)
  return _internal_children_objects(index);
}
inline ::serial::GameObject* BasicGameObject::_internal_add_children_objects() {
  return children_objects_.Add();
}
inline ::serial::GameObject* BasicGameObject::add_children_objects() {
  ::serial::GameObject* _add = _internal_add_children_objects();
  // @@protoc_insertion_point(field_add:serial.BasicGameObject.children_objects)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::serial::GameObject >&
BasicGameObject::children_objects() const {
  // @@protoc_insertion_point(field_list:serial.BasicGameObject.children_objects)
  return children_objects_;
}

// repeated .serial.Script children_scripts = 2;
inline int BasicGameObject::_internal_children_scripts_size() const {
  return children_scripts_.size();
}
inline int BasicGameObject::children_scripts_size() const {
  return _internal_children_scripts_size();
}
inline void BasicGameObject::clear_children_scripts() {
  children_scripts_.Clear();
}
inline ::serial::Script* BasicGameObject::mutable_children_scripts(int index) {
  // @@protoc_insertion_point(field_mutable:serial.BasicGameObject.children_scripts)
  return children_scripts_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::serial::Script >*
BasicGameObject::mutable_children_scripts() {
  // @@protoc_insertion_point(field_mutable_list:serial.BasicGameObject.children_scripts)
  return &children_scripts_;
}
inline const ::serial::Script& BasicGameObject::_internal_children_scripts(int index) const {
  return children_scripts_.Get(index);
}
inline const ::serial::Script& BasicGameObject::children_scripts(int index) const {
  // @@protoc_insertion_point(field_get:serial.BasicGameObject.children_scripts)
  return _internal_children_scripts(index);
}
inline ::serial::Script* BasicGameObject::_internal_add_children_scripts() {
  return children_scripts_.Add();
}
inline ::serial::Script* BasicGameObject::add_children_scripts() {
  ::serial::Script* _add = _internal_add_children_scripts();
  // @@protoc_insertion_point(field_add:serial.BasicGameObject.children_scripts)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::serial::Script >&
BasicGameObject::children_scripts() const {
  // @@protoc_insertion_point(field_list:serial.BasicGameObject.children_scripts)
  return children_scripts_;
}

// repeated string tags = 3;
inline int BasicGameObject::_internal_tags_size() const {
  return tags_.size();
}
inline int BasicGameObject::tags_size() const {
  return _internal_tags_size();
}
inline void BasicGameObject::clear_tags() {
  tags_.Clear();
}
inline std::string* BasicGameObject::add_tags() {
  std::string* _s = _internal_add_tags();
  // @@protoc_insertion_point(field_add_mutable:serial.BasicGameObject.tags)
  return _s;
}
inline const std::string& BasicGameObject::_internal_tags(int index) const {
  return tags_.Get(index);
}
inline const std::string& BasicGameObject::tags(int index) const {
  // @@protoc_insertion_point(field_get:serial.BasicGameObject.tags)
  return _internal_tags(index);
}
inline std::string* BasicGameObject::mutable_tags(int index) {
  // @@protoc_insertion_point(field_mutable:serial.BasicGameObject.tags)
  return tags_.Mutable(index);
}
inline void BasicGameObject::set_tags(int index, const std::string& value) {
  tags_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:serial.BasicGameObject.tags)
}
inline void BasicGameObject::set_tags(int index, std::string&& value) {
  tags_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:serial.BasicGameObject.tags)
}
inline void BasicGameObject::set_tags(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  tags_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:serial.BasicGameObject.tags)
}
inline void BasicGameObject::set_tags(int index, const char* value, size_t size) {
  tags_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:serial.BasicGameObject.tags)
}
inline std::string* BasicGameObject::_internal_add_tags() {
  return tags_.Add();
}
inline void BasicGameObject::add_tags(const std::string& value) {
  tags_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:serial.BasicGameObject.tags)
}
inline void BasicGameObject::add_tags(std::string&& value) {
  tags_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:serial.BasicGameObject.tags)
}
inline void BasicGameObject::add_tags(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  tags_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:serial.BasicGameObject.tags)
}
inline void BasicGameObject::add_tags(const char* value, size_t size) {
  tags_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:serial.BasicGameObject.tags)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
BasicGameObject::tags() const {
  // @@protoc_insertion_point(field_list:serial.BasicGameObject.tags)
  return tags_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
BasicGameObject::mutable_tags() {
  // @@protoc_insertion_point(field_mutable_list:serial.BasicGameObject.tags)
  return &tags_;
}

// .serial.RenderLayer render_layer = 7;
inline void BasicGameObject::clear_render_layer() {
  render_layer_ = 0;
}
inline ::serial::RenderLayer BasicGameObject::_internal_render_layer() const {
  return static_cast< ::serial::RenderLayer >(render_layer_);
}
inline ::serial::RenderLayer BasicGameObject::render_layer() const {
  // @@protoc_insertion_point(field_get:serial.BasicGameObject.render_layer)
  return _internal_render_layer();
}
inline void BasicGameObject::_internal_set_render_layer(::serial::RenderLayer value) {
  
  render_layer_ = value;
}
inline void BasicGameObject::set_render_layer(::serial::RenderLayer value) {
  _internal_set_render_layer(value);
  // @@protoc_insertion_point(field_set:serial.BasicGameObject.render_layer)
}

// .serial.Sprite sprite = 4;
inline bool BasicGameObject::_internal_has_sprite() const {
  return this != internal_default_instance() && sprite_ != nullptr;
}
inline bool BasicGameObject::has_sprite() const {
  return _internal_has_sprite();
}
inline void BasicGameObject::clear_sprite() {
  if (GetArenaForAllocation() == nullptr && sprite_ != nullptr) {
    delete sprite_;
  }
  sprite_ = nullptr;
}
inline const ::serial::Sprite& BasicGameObject::_internal_sprite() const {
  const ::serial::Sprite* p = sprite_;
  return p != nullptr ? *p : reinterpret_cast<const ::serial::Sprite&>(
      ::serial::_Sprite_default_instance_);
}
inline const ::serial::Sprite& BasicGameObject::sprite() const {
  // @@protoc_insertion_point(field_get:serial.BasicGameObject.sprite)
  return _internal_sprite();
}
inline void BasicGameObject::unsafe_arena_set_allocated_sprite(
    ::serial::Sprite* sprite) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sprite_);
  }
  sprite_ = sprite;
  if (sprite) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:serial.BasicGameObject.sprite)
}
inline ::serial::Sprite* BasicGameObject::release_sprite() {
  
  ::serial::Sprite* temp = sprite_;
  sprite_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::serial::Sprite* BasicGameObject::unsafe_arena_release_sprite() {
  // @@protoc_insertion_point(field_release:serial.BasicGameObject.sprite)
  
  ::serial::Sprite* temp = sprite_;
  sprite_ = nullptr;
  return temp;
}
inline ::serial::Sprite* BasicGameObject::_internal_mutable_sprite() {
  
  if (sprite_ == nullptr) {
    auto* p = CreateMaybeMessage<::serial::Sprite>(GetArenaForAllocation());
    sprite_ = p;
  }
  return sprite_;
}
inline ::serial::Sprite* BasicGameObject::mutable_sprite() {
  ::serial::Sprite* _msg = _internal_mutable_sprite();
  // @@protoc_insertion_point(field_mutable:serial.BasicGameObject.sprite)
  return _msg;
}
inline void BasicGameObject::set_allocated_sprite(::serial::Sprite* sprite) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete sprite_;
  }
  if (sprite) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::serial::Sprite>::GetOwningArena(sprite);
    if (message_arena != submessage_arena) {
      sprite = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sprite, submessage_arena);
    }
    
  } else {
    
  }
  sprite_ = sprite;
  // @@protoc_insertion_point(field_set_allocated:serial.BasicGameObject.sprite)
}

// bool visible = 5;
inline void BasicGameObject::clear_visible() {
  visible_ = false;
}
inline bool BasicGameObject::_internal_visible() const {
  return visible_;
}
inline bool BasicGameObject::visible() const {
  // @@protoc_insertion_point(field_get:serial.BasicGameObject.visible)
  return _internal_visible();
}
inline void BasicGameObject::_internal_set_visible(bool value) {
  
  visible_ = value;
}
inline void BasicGameObject::set_visible(bool value) {
  _internal_set_visible(value);
  // @@protoc_insertion_point(field_set:serial.BasicGameObject.visible)
}

// .serial.Box2DType box2d_type = 6;
inline void BasicGameObject::clear_box2d_type() {
  box2d_type_ = 0;
}
inline ::serial::Box2DType BasicGameObject::_internal_box2d_type() const {
  return static_cast< ::serial::Box2DType >(box2d_type_);
}
inline ::serial::Box2DType BasicGameObject::box2d_type() const {
  // @@protoc_insertion_point(field_get:serial.BasicGameObject.box2d_type)
  return _internal_box2d_type();
}
inline void BasicGameObject::_internal_set_box2d_type(::serial::Box2DType value) {
  
  box2d_type_ = value;
}
inline void BasicGameObject::set_box2d_type(::serial::Box2DType value) {
  _internal_set_box2d_type(value);
  // @@protoc_insertion_point(field_set:serial.BasicGameObject.box2d_type)
}

// -------------------------------------------------------------------

// Position

// float x = 1;
inline void Position::clear_x() {
  x_ = 0;
}
inline float Position::_internal_x() const {
  return x_;
}
inline float Position::x() const {
  // @@protoc_insertion_point(field_get:serial.Position.x)
  return _internal_x();
}
inline void Position::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Position::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:serial.Position.x)
}

// float y = 2;
inline void Position::clear_y() {
  y_ = 0;
}
inline float Position::_internal_y() const {
  return y_;
}
inline float Position::y() const {
  // @@protoc_insertion_point(field_get:serial.Position.y)
  return _internal_y();
}
inline void Position::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Position::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:serial.Position.y)
}

// -------------------------------------------------------------------

// Sprite_Scale

// float scale_x = 1;
inline void Sprite_Scale::clear_scale_x() {
  scale_x_ = 0;
}
inline float Sprite_Scale::_internal_scale_x() const {
  return scale_x_;
}
inline float Sprite_Scale::scale_x() const {
  // @@protoc_insertion_point(field_get:serial.Sprite.Scale.scale_x)
  return _internal_scale_x();
}
inline void Sprite_Scale::_internal_set_scale_x(float value) {
  
  scale_x_ = value;
}
inline void Sprite_Scale::set_scale_x(float value) {
  _internal_set_scale_x(value);
  // @@protoc_insertion_point(field_set:serial.Sprite.Scale.scale_x)
}

// float scale_y = 2;
inline void Sprite_Scale::clear_scale_y() {
  scale_y_ = 0;
}
inline float Sprite_Scale::_internal_scale_y() const {
  return scale_y_;
}
inline float Sprite_Scale::scale_y() const {
  // @@protoc_insertion_point(field_get:serial.Sprite.Scale.scale_y)
  return _internal_scale_y();
}
inline void Sprite_Scale::_internal_set_scale_y(float value) {
  
  scale_y_ = value;
}
inline void Sprite_Scale::set_scale_y(float value) {
  _internal_set_scale_y(value);
  // @@protoc_insertion_point(field_set:serial.Sprite.Scale.scale_y)
}

// -------------------------------------------------------------------

// Sprite

// string texture_path = 1;
inline void Sprite::clear_texture_path() {
  texture_path_.ClearToEmpty();
}
inline const std::string& Sprite::texture_path() const {
  // @@protoc_insertion_point(field_get:serial.Sprite.texture_path)
  return _internal_texture_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Sprite::set_texture_path(ArgT0&& arg0, ArgT... args) {
 
 texture_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:serial.Sprite.texture_path)
}
inline std::string* Sprite::mutable_texture_path() {
  std::string* _s = _internal_mutable_texture_path();
  // @@protoc_insertion_point(field_mutable:serial.Sprite.texture_path)
  return _s;
}
inline const std::string& Sprite::_internal_texture_path() const {
  return texture_path_.Get();
}
inline void Sprite::_internal_set_texture_path(const std::string& value) {
  
  texture_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Sprite::_internal_mutable_texture_path() {
  
  return texture_path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Sprite::release_texture_path() {
  // @@protoc_insertion_point(field_release:serial.Sprite.texture_path)
  return texture_path_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Sprite::set_allocated_texture_path(std::string* texture_path) {
  if (texture_path != nullptr) {
    
  } else {
    
  }
  texture_path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), texture_path,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (texture_path_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    texture_path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:serial.Sprite.texture_path)
}

// .serial.Position position = 2;
inline bool Sprite::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool Sprite::has_position() const {
  return _internal_has_position();
}
inline void Sprite::clear_position() {
  if (GetArenaForAllocation() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::serial::Position& Sprite::_internal_position() const {
  const ::serial::Position* p = position_;
  return p != nullptr ? *p : reinterpret_cast<const ::serial::Position&>(
      ::serial::_Position_default_instance_);
}
inline const ::serial::Position& Sprite::position() const {
  // @@protoc_insertion_point(field_get:serial.Sprite.position)
  return _internal_position();
}
inline void Sprite::unsafe_arena_set_allocated_position(
    ::serial::Position* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:serial.Sprite.position)
}
inline ::serial::Position* Sprite::release_position() {
  
  ::serial::Position* temp = position_;
  position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::serial::Position* Sprite::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:serial.Sprite.position)
  
  ::serial::Position* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::serial::Position* Sprite::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::serial::Position>(GetArenaForAllocation());
    position_ = p;
  }
  return position_;
}
inline ::serial::Position* Sprite::mutable_position() {
  ::serial::Position* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:serial.Sprite.position)
  return _msg;
}
inline void Sprite::set_allocated_position(::serial::Position* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::serial::Position>::GetOwningArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:serial.Sprite.position)
}

// .serial.Sprite.Scale scale = 5;
inline bool Sprite::_internal_has_scale() const {
  return this != internal_default_instance() && scale_ != nullptr;
}
inline bool Sprite::has_scale() const {
  return _internal_has_scale();
}
inline void Sprite::clear_scale() {
  if (GetArenaForAllocation() == nullptr && scale_ != nullptr) {
    delete scale_;
  }
  scale_ = nullptr;
}
inline const ::serial::Sprite_Scale& Sprite::_internal_scale() const {
  const ::serial::Sprite_Scale* p = scale_;
  return p != nullptr ? *p : reinterpret_cast<const ::serial::Sprite_Scale&>(
      ::serial::_Sprite_Scale_default_instance_);
}
inline const ::serial::Sprite_Scale& Sprite::scale() const {
  // @@protoc_insertion_point(field_get:serial.Sprite.scale)
  return _internal_scale();
}
inline void Sprite::unsafe_arena_set_allocated_scale(
    ::serial::Sprite_Scale* scale) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(scale_);
  }
  scale_ = scale;
  if (scale) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:serial.Sprite.scale)
}
inline ::serial::Sprite_Scale* Sprite::release_scale() {
  
  ::serial::Sprite_Scale* temp = scale_;
  scale_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::serial::Sprite_Scale* Sprite::unsafe_arena_release_scale() {
  // @@protoc_insertion_point(field_release:serial.Sprite.scale)
  
  ::serial::Sprite_Scale* temp = scale_;
  scale_ = nullptr;
  return temp;
}
inline ::serial::Sprite_Scale* Sprite::_internal_mutable_scale() {
  
  if (scale_ == nullptr) {
    auto* p = CreateMaybeMessage<::serial::Sprite_Scale>(GetArenaForAllocation());
    scale_ = p;
  }
  return scale_;
}
inline ::serial::Sprite_Scale* Sprite::mutable_scale() {
  ::serial::Sprite_Scale* _msg = _internal_mutable_scale();
  // @@protoc_insertion_point(field_mutable:serial.Sprite.scale)
  return _msg;
}
inline void Sprite::set_allocated_scale(::serial::Sprite_Scale* scale) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete scale_;
  }
  if (scale) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::serial::Sprite_Scale>::GetOwningArena(scale);
    if (message_arena != submessage_arena) {
      scale = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, scale, submessage_arena);
    }
    
  } else {
    
  }
  scale_ = scale;
  // @@protoc_insertion_point(field_set_allocated:serial.Sprite.scale)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace serial

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::serial::RenderLayer> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::serial::RenderLayer>() {
  return ::serial::RenderLayer_descriptor();
}
template <> struct is_proto_enum< ::serial::Box2DType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::serial::Box2DType>() {
  return ::serial::Box2DType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_scene_2eproto
